Repository codeit-bootcamp-frontend/0-crypto-meter-technokings, pull requests merged in 2023-05, with the labels that each got.

#1 :tada: 보일러 플레이트 제작
  .eslintrc.cjs
  .gitignore
  .prettierrc
  docker-compose.yml
  index.html
  netlify.toml
  package-lock.json
  package.json
  public/favicon.svg
  src/App.css
  src/App.jsx
  src/assets/fonts/Pretendard-Black.otf
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard-Thin.otf
  src/components/index.js
  src/index.css
  src/main.jsx
  src/styles/colors.js
  vite.config.js
Labels: initial

#11 컴포넌트 스켈레톤 제작 - 마이크로 컴포넌트 제작 및 스타일 시스템 구축
  .eslintrc.cjs
  docker-compose.yml
  src/App.css
  src/main.jsx
  src/styles/block.style.js
  src/styles/colors.js
  src/styles/micro-components/StyledButton.js
  src/styles/micro-components/StyledDiv.js
  src/styles/micro-components/StyledHeadings.js
  src/styles/micro-components/StyledText.js
  src/styles/text.style.js
Labels: 🚀 feature

#12 컴포넌트 스켈레톤 제작 - 인터페이스 설계
  src/data/interface.js
  src/data/interface.prop.type.ts
  src/data/mock.js
Labels: 🚀 feature

#14 Refactor/interface design/#13
  package-lock.json
  package.json
  src/data/interface.js
  src/data/interface.prop.type.ts
  src/data/interface.prop.types.jsx
Labels: 🛠 refactor

#16 컴포넌트 스켈레톤 제작 - SVG 컴포넌트 추가
  src/components/SVGComponents/CloseIcon.jsx
  src/components/SVGComponents/DropdownHandleIcon.jsx
  src/components/SVGComponents/FacebookLogo.jsx
  src/components/SVGComponents/FilterIcon.jsx
  src/components/SVGComponents/KakaoLogo.jsx
  src/components/SVGComponents/MainLogo.jsx
  src/components/SVGComponents/NextIcon.jsx
  src/components/SVGComponents/OrderIcon.jsx
  src/components/SVGComponents/PrevIcon.jsx
  src/components/SVGComponents/RestoreIcon.jsx
  src/components/SVGComponents/ShareIcon.jsx
  src/components/index.js
Labels: 🚀 feature

#28 Dropdown 및 Select 컴포넌트 추가
  jsconfig.json
  src/components/Common/Dropdown/Dropdown.jsx
  src/components/Common/Dropdown/DropdownList.jsx
  src/components/Common/Dropdown/DropdownListItem.jsx
  src/components/Common/Dropdown/DropdownPresenter.jsx
  src/components/Common/Select/Select.jsx
  src/components/Common/Select/SelectList.jsx
  src/components/Common/Select/SelectListItem.jsx
  src/components/Common/Select/SelectPresenter.jsx
  src/components/SVGComponents/DropdownHandleIcon.jsx
  src/components/index.js
  vite.config.js
Labels: 🚀 feature

#32 :recycle: 루트 폰트 62.5%로 보정
  src/App.css
  src/styles/text.style.js
Labels: 🛠 refactor

#33 페이지 구성하기 - Gnb
  src/App.css
  src/App.jsx
  src/components/Gnb/Gnb.jsx
  src/components/Gnb/GnbButton.jsx
  src/components/Gnb/GnbPresenter.jsx
  src/components/Gnb/SearchHistory/SearchHistory.jsx
  src/components/Gnb/SearchHistory/SearchHistoryList.jsx
  src/components/Gnb/SearchHistory/SearchHistoryListItem.jsx
  src/components/Gnb/Select/Select.jsx
  src/components/Gnb/Select/SelectList.jsx
  src/components/Gnb/Select/SelectListItem.jsx
  src/components/Gnb/Select/SelectPresenter.jsx
  src/components/SearchHistoryButton/SearchHistoryButton.jsx
  src/components/index.js
  src/styles/micro-components/StyledButton.js
Labels: 🚀 feature

#35 :wrench: Eslint linebreak 룰 수정
  .eslintrc.cjs
Labels: 🚑 hotfix

#37 InputBoard 컴포넌트 추가
  .eslintrc.cjs
  README.md
  src/App.css
  src/App.jsx
  src/components/InputBoard/DateInput/DateInput.jsx
  src/components/InputBoard/Dropdown/Dropdown.jsx
  src/components/InputBoard/Dropdown/DropdownList.jsx
  src/components/InputBoard/Dropdown/DropdownListItem.jsx
  src/components/InputBoard/Dropdown/DropdownPresenter.jsx
  src/components/InputBoard/IncreaseMoneyButton/IncreaseMoneyButton.jsx
  src/components/InputBoard/InputBoard.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/InputBoard/MoneyInput/MoneyInput.jsx
  src/components/index.js
  src/data/interface.md
  src/hooks/useMediaQuery.js
  src/styles/block.style.js
  src/styles/micro-components/StyledButton.js
  src/styles/micro-components/StyledDiv.js
  src/utils/formatMoney.js
Labels: 🚀 feature

#39 (리팩토링)페이지 구성하기 - Gnb
  src/App.jsx
  src/components/Gnb/GnbButton.jsx
  src/components/Gnb/GnbPresenter.jsx
  src/components/Gnb/SearchHistory/SearchHistory.jsx
  src/components/Gnb/SearchHistory/SearchHistoryList.jsx
  src/components/Gnb/SearchHistory/SearchHistoryListItem.jsx
  src/components/Gnb/Select/SelectPresenter.jsx
  src/components/InputBoard/DateInput/DateInput.jsx
  src/components/InputBoard/Dropdown/Dropdown.jsx
  src/components/InputBoard/Dropdown/DropdownList.jsx
  src/components/InputBoard/Dropdown/DropdownListItem.jsx
  src/components/InputBoard/Dropdown/DropdownPresenter.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/InputBoard/MoneyInput/MoneyInput.jsx
  src/components/index.js
Labels: 🛠 refactor

#40 페이지 구성하기 - Chart 컴포넌트 작성
  package-lock.json
  package.json
  src/App.jsx
  src/components/CoinChart/CoinChart.jsx
  src/components/CoinChart/CoinChartArea.jsx
  src/components/CoinChart/CoinChartCanvas.jsx
  src/components/CoinChart/CoinChartCustomTooltip.jsx
  src/components/CoinChart/CoinChartHeader.jsx
  src/components/CoinChart/CoinChartPresenter.jsx
  src/components/CoinChart/CoinHistoryUserSelect.jsx
  src/components/CoinChart/CoinSelectDurationChip.jsx
  src/components/CoinChart/chart.data.js
Labels: 🚀 feature

#41 DateInput 컴포넌트 제작
  package-lock.json
  package.json
  src/components/CoinChart/CoinChartArea.jsx
  src/components/CoinChart/CoinChartCanvas.jsx
  src/components/CoinChart/CoinChartHeader.jsx
  src/components/CoinChart/CoinChartPresenter.jsx
  src/components/CoinChart/CoinHistoryUserSelect.jsx
  src/components/CoinChart/CoinSelectDurationChip.jsx
  src/components/Gnb/Select/SelectListItem.jsx
  src/components/Gnb/Select/SelectPresenter.jsx
  src/components/InputBoard/DateInput/DateInput.jsx
  src/components/InputBoard/Dropdown/Dropdown.jsx
  src/components/InputBoard/Dropdown/DropdownList.jsx
  src/components/InputBoard/Dropdown/DropdownPresenter.jsx
  src/components/InputBoard/IncreaseMoneyButton/IncreaseMoneyButton.jsx
  src/components/InputBoard/InputBoard.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/InputBoard/MoneyInput/MoneyInput.jsx
  src/components/PriceChange/PriceChange.jsx
  src/components/SVGComponents/FacebookLogo.jsx
  src/components/SVGComponents/FilterIcon.jsx
  src/components/SVGComponents/KakaoLogo.jsx
  src/components/SVGComponents/MainLogo.jsx
  src/components/SVGComponents/NextIcon.jsx
  src/components/SVGComponents/PrevIcon.jsx
  src/components/SVGComponents/RestoreIcon.jsx
  src/components/SVGComponents/ShareIcon.jsx
  src/components/SelectDurationChip/SelectDurationChip.jsx
  src/data/interface.md
  src/hooks/useOutsideClick.js
  src/styles/text.style.js
  src/utils/formatDate.js
  src/utils/formatMoney.js
Labels: 🚀 feature

#44 기능 구현하기 - sns 공유하기 기능 및 차트 컴포넌트 1차 리팩토링
  .github/ISSUE_TEMPLATE/bug-이슈.md
  .github/ISSUE_TEMPLATE/feature-이슈.md
  .gitignore
  index.html
  public/null_chart.png
  src/components/CoinChart/CoinChart.jsx
  src/components/CoinChart/CoinChartArea.jsx
  src/components/CoinChart/CoinChartCanvas.jsx
  src/components/CoinChart/CoinChartCustomTooltip.jsx
  src/components/CoinChart/CoinChartHeader.jsx
  src/components/CoinChart/CoinChartPresenter.jsx
  src/components/CoinChart/CoinHistoryUserSelect.jsx
  src/components/CoinChart/CoinSelectDurationChip.jsx
  src/components/CoinChart/chart.data.js
  src/components/SVGComponents/FacebookLogo.jsx
  src/components/SVGComponents/KakaoLogo.jsx
  src/components/SVGComponents/ShareIcon.jsx
  src/services/kakao/share.kakao.js
Labels: 🚀 feature, 🛠 refactor

#46 ✅ 페이지 구성하기 - 테이블
  src/App.css
  src/App.jsx
  src/components/Gnb/GnbButton.jsx
  src/components/Gnb/GnbPresenter.jsx
  src/components/Gnb/SearchHistory/SearchHistory.jsx
  src/components/Gnb/SearchHistory/SearchHistoryList.jsx
  src/components/Gnb/SearchHistory/SearchHistoryListItem.jsx
  src/components/Gnb/SearchHistory/SearchHistoryPresenter.jsx
  src/components/Gnb/Select/SelectPresenter.jsx
  src/components/SVGComponents/MainLogo.jsx
  src/components/SVGComponents/NextIcon.jsx
  src/components/SVGComponents/OrderIcon.jsx
  src/components/SVGComponents/PrevIcon.jsx
  src/components/TableSection/Table/Pagination.jsx
  src/components/TableSection/Table/PriceChange/PriceChange.jsx
  src/components/TableSection/Table/Table.jsx
  src/components/TableSection/Table/TableHeader.jsx
  src/components/TableSection/Table/TablePresenter.jsx
  src/components/TableSection/Table/TableRow.jsx
  src/components/TableSection/TableSection.jsx
  src/components/index.js
  src/data/mockMarkets.js
  src/styles/colors.js
  src/utils/formatMoney.js
Labels: 🚀 feature

#51 :recycle: CoinStore 액션 기능 축소
  src/stores/coinStore.js
Labels: 🛠 refactor, 🪓 Fix

#52 Feature/config layout/#48 기능 구현하기 - 전체 레이아웃 구성
  src/App.css
  src/App.jsx
  src/components/CoinChart/CoinChart.jsx
  src/components/CoinChart/CoinChartPresenter.jsx
  src/components/CoinChart/CoinChartWrapper.jsx
  src/components/CoinChart/DefaultChartImage.jsx
  src/components/Gnb/GnbPresenter.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/TableSection/TableSection.jsx
  src/components/index.js
Labels: 🚀 feature

#55 :sparkles: 기능 구현하기 - API
  src/hooks/useAsync.js
  src/services/api/index.js
Labels: 🚀 feature

#54 InputBoard에 기능 추가
  src/components/Gnb/SearchHistory/SearchHistory.jsx
  src/components/Gnb/SearchHistory/SearchHistoryListItem.jsx
  src/components/InputBoard/DateInput/DateInput.jsx
  src/components/InputBoard/Dropdown/Dropdown.jsx
  src/components/InputBoard/Dropdown/DropdownList.jsx
  src/components/InputBoard/Dropdown/DropdownListItem.jsx
  src/components/InputBoard/Dropdown/DropdownPresenter.jsx
  src/components/InputBoard/IncreaseMoneyButton/IncreaseMoneyButton.jsx
  src/components/InputBoard/InputBoard.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/InputBoard/MoneyInput/MoneyInput.jsx
  src/data/dropdownList.js
  src/hooks/useMediaQuery.js
  src/stores/coinStore.js
  src/stores/userInputStore.js
Labels: 🚀 feature, 🛠 refactor

#60 :sparkles: CoinStore에 getPage 액션 추가
  src/stores/coinStore.js
Labels: 🚀 feature

#62 :sparkles: CoinStore에 getPageSlice 액션 추가
  src/stores/coinStore.js
Labels: 🚀 feature

#65 Gnb 기능 추가
  src/components/Gnb/Gnb.jsx
  src/components/Gnb/GnbPresenter.jsx
  src/components/Gnb/SearchHistory/FilterOptionList/FilterOptionList.jsx
  src/components/Gnb/SearchHistory/FilterOptionList/FilterOptionListItem.jsx
  src/components/Gnb/SearchHistory/SearchHistory.jsx
  src/components/Gnb/SearchHistory/SearchHistoryList.jsx
  src/components/Gnb/SearchHistory/SearchHistoryPresenter.jsx
  src/components/Gnb/Select/Select.jsx
  src/components/Gnb/Select/SelectList.jsx
  src/components/Gnb/Select/SelectListItem.jsx
  src/components/Gnb/Select/SelectPresenter.jsx
  src/components/InputBoard/Dropdown/Dropdown.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/SVGComponents/SelectFilterIcon.jsx
  src/components/index.js
  src/data/currencyOptions.js
  src/hooks/useOutsideClick.js
Labels: 🚀 feature

#63 차트 컴포넌트 API 연동 및 store 연결
  package-lock.json
  package.json
  src/components/CoinChart/CoinChart.jsx
  src/components/CoinChart/CoinChartLoader.jsx
  src/components/CoinChart/CoinChartPresenter.jsx
  src/components/CoinChart/CoinChartWrapper.jsx
  src/components/CoinChart/DefaultChartImage.jsx
  src/components/CoinChart/ErrorChartImage.jsx
  src/hooks/useGetData.js
  src/services/api/index.js
Labels: 🚀 feature

#67 전체 레이아웃 수정
  src/App.jsx
  src/components/CoinChart/CoinChartLoader.jsx
  src/components/CoinChart/CoinChartPresenter.jsx
  src/components/CoinChart/DefaultChartImage.jsx
  src/components/Gnb/GnbPresenter.jsx
  src/components/Gnb/Select/Select.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/TableSection/TableSection.jsx
Labels: 🪓 Fix

#68 ✅ InputBoard Api 연동 리팩토링
  src/App.css
  src/components/Gnb/Gnb.jsx
  src/components/InputBoard/DateInput/DateInput.jsx
  src/components/InputBoard/Dropdown/Dropdown.jsx
  src/components/InputBoard/IncreaseMoneyButton/IncreaseMoneyButton.jsx
  src/components/InputBoard/InputBoard.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/InputBoard/MoneyInput/MoneyInput.jsx
  src/stores/mockData.js
  src/stores/userInputStore.js
  src/styles/micro-components/StyledHeadings.js
  src/utils/scrollTop.js
Labels: 🐛 bug, 🚀 feature, 🛠 refactor, 🪓 Fix

#69 ✅ 기능 구현하기 - 페이지네이션
  src/components/SVGComponents/FirstIcon.jsx
  src/components/SVGComponents/LastIcon.jsx
  src/components/SVGComponents/NextIcon.jsx
  src/components/SVGComponents/OrderIcon.jsx
  src/components/SVGComponents/PrevIcon.jsx
  src/components/TableSection/Table/Pagination.jsx
  src/components/TableSection/Table/Table.jsx
  src/components/TableSection/Table/TablePresenter.jsx
  src/components/TableSection/Table/TableRow.jsx
  src/hooks/useAsync.js
  src/hooks/useMarketData.js
  src/stores/coinStore.js
Labels: 🚀 feature

#70 :ambulance: CalculatedMoney를 Number로 파싱하여 세팅
  src/stores/userInputStore.js
Labels: 🚑 hotfix

#72 :lipstick: UI 깨지는 현상들 전반 수정
  index.html
  public/favicon.webp
  public/null_chart.png
  src/App.css
  src/assets/fonts/Pretendard-Black.otf
  src/assets/fonts/Pretendard-Bold.otf
  src/assets/fonts/Pretendard-ExtraBold.otf
  src/assets/fonts/Pretendard-ExtraLight.otf
  src/assets/fonts/Pretendard-Light.otf
  src/assets/fonts/Pretendard-Medium.otf
  src/assets/fonts/Pretendard-Regular.otf
  src/assets/fonts/Pretendard-SemiBold.otf
  src/assets/fonts/Pretendard-Thin.otf
  src/assets/null_chart.webp
  src/components/CoinChart/CoinChart.jsx
  src/components/CoinChart/CoinChartHeader.jsx
  src/components/CoinChart/CoinHistoryUserSelect.jsx
  src/components/CoinChart/DefaultChartImage.jsx
  src/components/Gnb/GnbPresenter.jsx
  src/components/InputBoard/DateInput/DateInput.jsx
  src/components/InputBoard/InputBoard.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/components/InputBoard/MoneyInput/MoneyInput.jsx
  src/data/interface.md
  src/data/mockMarkets.js
  src/services/kakao/share.kakao.js
  src/stores/userInputStore.js
Labels: 🚑 hotfix

#73 ✅ 테이블 리팩토링
  src/assets/imageNotExist.svg
  src/components/TableSection/Table/PriceChange/PriceChange.jsx
  src/components/TableSection/Table/TablePresenter.jsx
  src/components/TableSection/Table/TableRow.jsx
  src/hooks/useMarketData.js
  src/stores/coinStore.js
  src/utils/formatMoney.js
Labels: 🛠 refactor, 🪓 Fix

#76 :children_crossing: InputBoard 초기날짜 1년 전으로 수정
  src/components/InputBoard/InputBoard.jsx
  src/stores/userInputStore.js
Labels: 🚑 hotfix

#78 🚑 입력 중 화폐단위 변경, 초기화 시 InputBoard 데이터 안바뀌는 버그 수정
  src/components/Gnb/Gnb.jsx
  src/components/InputBoard/InputBoard.jsx
  src/components/InputBoard/InputBoardPresenter.jsx
  src/stores/userInputStore.js
Labels: 🚑 hotfix

#79 :bug: 끝페이지 처리가 제대로 안되는 버그 해결
  src/hooks/useMarketData.js
Labels: 🐛 bug

#80 Update README.md
  README.md
Labels: documentation
